# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-25 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20170823_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='is_favorite',
        ),
        migrations.AddField(
            model_name='song',
            name='myfile',
            field=models.FileField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
