# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-25 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20170825_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='myfile',
            field=models.FileField(default='C:\\New folder\\mp3\\Shot.mp3', upload_to=''),
        ),
    ]
